apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmlog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dmlog.labels" . | nindent 4 }}
    component: backend
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dmlog.selectorLabels" . | nindent 4 }}
    component: backend