import mongoose from 'mongoose';
import { createClient } from 'redis';
import { logger } from '@/utils/logger';

export interface IStreamSession {
  _id?: string;
  title: string;
  description?: string;
  platforms: string[];
  startTime: Date;
  endTime?: Date;
  duration?: number;
  status: 'scheduled' | 'live' | 'ended' | 'cancelled';
  viewerCounts: {
    [platform: string]: {
      current: number;
      peak: number;
      average: number;
    };
  };
  revenue: {
    donations: number;
    subscriptions: number;
    tips: number;
    total: number;
  };
  metadata: {
    campaign?: string;
    sessionNumber?: number;
    characters?: string[];
    tags?: string[];
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface IViewer {
  _id?: string;
  username: string;
  platforms: string[];
  firstSeen: Date;
  lastSeen: Date;
  totalWatchTime: number;
  isSubscriber: boolean;
  isFollower: boolean;
  donations: number;
  engagement: {
    chatMessages: number;
    polls: number;
    reactions: number;
  };
  preferences: {
    favoriteCharacters?: string[];
    notifications: boolean;
  };
}

export interface IDonation {
  _id?: string;
  platform: string;
  amount: number;
  currency: string;
  donorName: string;
  message?: string;
  timestamp: Date;
  streamSession?: string;
  status: 'pending' | 'completed' | 'failed';
  metadata: {
    isAnonymous: boolean;
    campaign?: string;
  };
}

export interface IHighlight {
  _id?: string;
  title: string;
  description?: string;
  timestamp: number;
  duration: number;
  streamSession: string;
  type: 'combat' | 'roleplay' | 'dice-roll' | 'funny' | 'emotional' | 'important';
  tags: string[];
  thumbnailUrl?: string;
  videoUrl?: string;
  isAutoGenerated: boolean;
  confidence: number;
  createdAt: Date;
}

// Mongoose Schemas
const StreamSessionSchema = new mongoose.Schema<IStreamSession>({
  title: { type: String, required: true },
  description: { type: String },
  platforms: [{ type: String, required: true }],
  startTime: { type: Date, required: true },
  endTime: { type: Date },
  duration: { type: Number },
  status: {
    type: String,
    enum: ['scheduled', 'live', 'ended', 'cancelled'],
    default: 'scheduled'
  },
  viewerCounts: {
    type: Map,
    of: {
      current: { type: Number, default: 0 },
      peak: { type: Number, default: 0 },
      average: { type: Number, default: 0 }
    }
  },
  revenue: {
    donations: { type: Number, default: 0 },
    subscriptions: { type: Number, default: 0 },
    tips: { type: Number, default: 0 },
    total: { type: Number, default: 0 }
  },
  metadata: {
    campaign: { type: String },
    sessionNumber: { type: Number },
    characters: [{ type: String }],
    tags: [{ type: String }]
  }
}, {
  timestamps: true
});

const ViewerSchema = new mongoose.Schema<IViewer>({
  username: { type: String, required: true, unique: true },
  platforms: [{ type: String, required: true }],
  firstSeen: { type: Date, default: Date.now },
  lastSeen: { type: Date, default: Date.now },
  totalWatchTime: { type: Number, default: 0 },
  isSubscriber: { type: Boolean, default: false },
  isFollower: { type: Boolean, default: false },
  donations: { type: Number, default: 0 },
  engagement: {
    chatMessages: { type: Number, default: 0 },
    polls: { type: Number, default: 0 },
    reactions: { type: Number, default: 0 }
  },
  preferences: {
    favoriteCharacters: [{ type: String }],
    notifications: { type: Boolean, default: true }
  }
});

const DonationSchema = new mongoose.Schema<IDonation>({
  platform: { type: String, required: true },
  amount: { type: Number, required: true },
  currency: { type: String, required: true, default: 'USD' },
  donorName: { type: String, required: true },
  message: { type: String },
  timestamp: { type: Date, default: Date.now },
  streamSession: { type: mongoose.Schema.Types.ObjectId, ref: 'StreamSession' },
  status: {
    type: String,
    enum: ['pending', 'completed', 'failed'],
    default: 'pending'
  },
  metadata: {
    isAnonymous: { type: Boolean, default: false },
    campaign: { type: String }
  }
});

const HighlightSchema = new mongoose.Schema<IHighlight>({
  title: { type: String, required: true },
  description: { type: String },
  timestamp: { type: Number, required: true },
  duration: { type: Number, required: true },
  streamSession: { type: mongoose.Schema.Types.ObjectId, ref: 'StreamSession', required: true },
  type: {
    type: String,
    enum: ['combat', 'roleplay', 'dice-roll', 'funny', 'emotional', 'important'],
    required: true
  },
  tags: [{ type: String }],
  thumbnailUrl: { type: String },
  videoUrl: { type: String },
  isAutoGenerated: { type: Boolean, default: false },
  confidence: { type: Number, min: 0, max: 1, default: 0.5 }
}, {
  timestamps: true
});

export class DatabaseService {
  private static instance: DatabaseService;
  private static redisClient: any;
  private static mongooseConnection: typeof mongoose;

  private constructor() {}

  public static getInstance(): DatabaseService {
    if (!DatabaseService.instance) {
      DatabaseService.instance = new DatabaseService();
    }
    return DatabaseService.instance;
  }

  public static async connect(): Promise<void> {
    try {
      // Connect to MongoDB
      DatabaseService.mongooseConnection = mongoose;
      await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/dnd-streaming-platform');
      logger.info('Connected to MongoDB');

      // Connect to Redis
      DatabaseService.redisClient = createClient({
        url: process.env.REDIS_URL || 'redis://localhost:6379'
      });

      DatabaseService.redisClient.on('error', (err) => {
        logger.error('Redis Client Error:', err);
      });

      DatabaseService.redisClient.on('connect', () => {
        logger.info('Connected to Redis');
      });

      await DatabaseService.redisClient.connect();

    } catch (error) {
      logger.error('Database connection failed:', error);
      throw error;
    }
  }

  public static async disconnect(): Promise<void> {
    try {
      await mongoose.disconnect();
      if (DatabaseService.redisClient) {
        await DatabaseService.redisClient.quit();
      }
      logger.info('Disconnected from databases');
    } catch (error) {
      logger.error('Database disconnection failed:', error);
      throw error;
    }
  }

  public static isConnected(): boolean {
    return mongoose.connection.readyState === 1 &&
           DatabaseService.redisClient?.isOpen === true;
  }

  // Stream Session methods
  public static async createStreamSession(sessionData: Partial<IStreamSession>): Promise<IStreamSession> {
    const StreamSession = mongoose.model<IStreamSession>('StreamSession', StreamSessionSchema);
    const session = new StreamSession(sessionData);
    return await session.save();
  }

  public static async getStreamSession(id: string): Promise<IStreamSession | null> {
    const StreamSession = mongoose.model<IStreamSession>('StreamSession', StreamSessionSchema);
    return await StreamSession.findById(id).populate('highlights');
  }

  public static async updateStreamSession(id: string, updateData: Partial<IStreamSession>): Promise<IStreamSession | null> {
    const StreamSession = mongoose.model<IStreamSession>('StreamSession', StreamSessionSchema);
    return await StreamSession.findByIdAndUpdate(id, updateData, { new: true });
  }

  public static async getActiveStreamSession(): Promise<IStreamSession | null> {
    const StreamSession = mongoose.model<IStreamSession>('StreamSession', StreamSessionSchema);
    return await StreamSession.findOne({ status: 'live' });
  }

  // Viewer methods
  public static async createOrUpdateViewer(viewerData: Partial<IViewer>): Promise<IViewer> {
    const Viewer = mongoose.model<IViewer>('Viewer', ViewerSchema);
    return await Viewer.findOneAndUpdate(
      { username: viewerData.username },
      viewerData,
      { upsert: true, new: true }
    );
  }

  public static async getViewer(username: string): Promise<IViewer | null> {
    const Viewer = mongoose.model<IViewer>('Viewer', ViewerSchema);
    return await Viewer.findOne({ username });
  }

  // Donation methods
  public static async createDonation(donationData: Partial<IDonation>): Promise<IDonation> {
    const Donation = mongoose.model<IDonation>('Donation', DonationSchema);
    const donation = new Donation(donationData);
    return await donation.save();
  }

  public static async getDonationsBySession(sessionId: string): Promise<IDonation[]> {
    const Donation = mongoose.model<IDonation>('Donation', DonationSchema);
    return await Donation.find({ streamSession: sessionId }).sort({ timestamp: -1 });
  }

  // Highlight methods
  public static async createHighlight(highlightData: Partial<IHighlight>): Promise<IHighlight> {
    const Highlight = mongoose.model<IHighlight>('Highlight', HighlightSchema);
    const highlight = new Highlight(highlightData);
    return await highlight.save();
  }

  public static async getHighlightsBySession(sessionId: string): Promise<IHighlight[]> {
    const Highlight = mongoose.model<IHighlight>('Highlight', HighlightSchema);
    return await Highlight.find({ streamSession: sessionId }).sort({ timestamp: 1 });
  }

  // Redis cache methods
  public static async cacheData(key: string, data: any, ttl: number = 3600): Promise<void> {
    try {
      await DatabaseService.redisClient.setEx(key, ttl, JSON.stringify(data));
    } catch (error) {
      logger.error('Redis cache error:', error);
    }
  }

  public static async getCachedData(key: string): Promise<any> {
    try {
      const data = await DatabaseService.redisClient.get(key);
      return data ? JSON.parse(data) : null;
    } catch (error) {
      logger.error('Redis cache retrieval error:', error);
      return null;
    }
  }

  public static async deleteCachedData(key: string): Promise<void> {
    try {
      await DatabaseService.redisClient.del(key);
    } catch (error) {
      logger.error('Redis cache deletion error:', error);
    }
  }

  // Analytics methods
  public static async getStreamAnalytics(dateRange: { start: Date; end: Date }): Promise<any> {
    const StreamSession = mongoose.model<IStreamSession>('StreamSession', StreamSessionSchema);
    const Donation = mongoose.model<IDonation>('Donation', DonationSchema);

    const sessions = await StreamSession.find({
      startTime: { $gte: dateRange.start, $lte: dateRange.end }
    });

    const donations = await Donation.aggregate([
      {
        $match: {
          timestamp: { $gte: dateRange.start, $lte: dateRange.end },
          status: 'completed'
        }
      },
      {
        $group: {
          _id: '$platform',
          totalAmount: { $sum: '$amount' },
          count: { $sum: 1 }
        }
      }
    ]);

    return {
      totalSessions: sessions.length,
      totalRevenue: sessions.reduce((sum, session) => sum + session.revenue.total, 0),
      totalViewers: sessions.reduce((sum, session) => {
        return sum + Array.from(session.viewerCounts.values())
          .reduce((platformSum, platform) => platformSum + platform.peak, 0);
      }, 0),
      donationsByPlatform: donations,
      averageSessionDuration: sessions.length > 0
        ? sessions.reduce((sum, session) => sum + (session.duration || 0), 0) / sessions.length
        : 0
    };
  }
}

export default DatabaseService;